language: cpp
compiler: clang
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq --fix-missing libasound2-dev libboost1.48-dev
  - ./scripts/travis_build_libcxx.sh
script: ./scripts/travis_build.sh
notifications:
  email: false
