language: cpp
compiler: clang
before_install:
  - sudo add-apt-repository -y ppa:apokluda/boost1.53
  - sudo apt-get update
  - sudo apt-get install -qq --fix-missing libasound2-dev libboost1.53-dev libboost-test1.53-dev libboost-serialization1.53-dev libboost-system1.53-dev libboost-date-time1.53-dev libboost-program-options1.53-dev
  - ./scripts/travis_build_libcxx.sh
script: ./scripts/travis_build.sh
notifications:
  email: false
