language: cpp
compiler: clang
before_install:
  - ./scripts/travis_build_libcxx.sh
  - sudo apt-get update
  - sudo apt-cache search boost
  - sudo apt-get install -qq --fix-missing libasound2-dev libboost1.53-dev
script: ./scripts/travis_build.sh
notifications:
  email: false
